Repository truenas/py-fenced, pull requests merged in 2024-09, with the labels that each got.

#46 NAS-131361 / 25.04 / more resilient disk enumeration
  fenced/utils.py
Labels: jira-high, backport-24.04.2.3, backport-24.04.0

#51 NAS-131395 / 25.04 / fix subtle regression in fenced
  fenced/utils.py
Labels: jira-high, backport-24.04.2.3, backport-24.10.0, backported

#54 NAS-131419 / 25.04 / greatly simplify disk enumeration in fenced
  fenced/main.py
  fenced/utils.py
Labels: jira

#55 NAS-131428 / 25.04 / Do not use ALUA internal disks in load_disks_from_sys_block
  fenced/utils.py
Labels: jira

#56 NAS-131432 / 25.04 / rename function to match reality
  fenced/utils.py
Labels: jira

#57 NAS-131450 / 24.10.0 / Revert recent work-around in fenced (it doesn't work)
  fenced/utils.py
Labels: jira-high, backport-24.04.2.3, backported
